// Publish the mp3s the listen page plays. renders/ is gitignored and the Pages build runs in CI, so the audio cannot
// travel in the repo: it goes to a GitHub release, once per song, and web/listen/published.json (committed) records
// what is up there. Needs the `gh` cli, authenticated.
// usage: node scripts/publish-audio.mjs [song ...]     (default: every mp3 in renders/ that matches a song)
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { songList } from '../server.mjs';

const ROOT = path.resolve(import.meta.dirname, '..');
const MANIFEST = path.join(ROOT, 'web', 'listen', 'published.json');
const man = JSON.parse(fs.readFileSync(MANIFEST, 'utf8'));
const gh = (...args) => execFileSync('gh', args, { cwd: ROOT, stdio: ['ignore', 'pipe', 'inherit'] }).toString().trim();

const asked = process.argv.slice(2).map((a) => path.basename(a));
const songs = songList().filter((s) => (asked.length ? asked.includes(s) || asked.includes(s.replace(/\.strudel$/, '')) : true));
const files = songs.map((s) => [s, `${s.replace(/\.strudel$/, '')}.mp3`]).filter(([, f]) => fs.existsSync(path.join(ROOT, 'renders', f)));
if (!files.length) { console.error(`nothing to publish: render one first, e.g. npm run render -- songs/demo.strudel --mp3`); process.exit(1); }

try { gh('release', 'view', man.tag); }
catch { gh('release', 'create', man.tag, '--title', 'song audio', '--notes', 'The mp3s the listen page plays. Generated by npm run render; see the repository for the songs themselves.'); }
for (const [, f] of files) { gh('release', 'upload', man.tag, path.join('renders', f), '--clobber'); console.log(`uploaded ${f}`); }

man.songs = [...new Set([...man.songs, ...files.map(([s]) => s)])].sort();
fs.writeFileSync(MANIFEST, `${JSON.stringify(man, null, 2)}\n`);
console.log(`web/listen/published.json now lists ${man.songs.length} songs; commit it so the deployed page knows.`);
