// Generates the skill's vocabulary reference from code so it cannot drift. usage: node scripts/vocab.mjs > .claude/skills/strudel/reference/vocab.md
import { AXES, PHASES, cells } from '../lib/axes.mjs';
import { DESCRIPTORS, OVERLAYS, MODIFIERS, HARMONY, MOTION } from '../lib/vocab.mjs';
import '../lib/layers.mjs';

const out = [];
out.push('# strudel-bench vocabulary (generated, do not edit)\n');
out.push('## Axes (0..1, 0.5 = layer baseline)\n');
out.push('| axis | kind | meaning | verification |', '|---|---|---|---|');
for (const a of AXES) out.push(`| ${a.name} | ${a.kind} | ${a.meaning} | ${a.verify.class}${a.verify.metric ? ': ' + a.verify.metric : ''} |`);
out.push('\n## Adapter cells (what each axis does per layer at 0.2 / 0.8)\n');
const layers = Object.keys(cells);
out.push(`| axis | ${layers.join(' | ')} |`, `|---|${layers.map(() => '---').join('|')}|`);
for (const a of AXES) out.push(`| ${a.name} | ${layers.map((L) => { const c = cells[L][a.name]; return c ? `${c.describe?.(0.5, 0.2) ?? 'yes'} / ${c.describe?.(0.5, 0.8) ?? 'yes'}` : '—'; }).join(' | ')} |`);
out.push(`\nPhases: ${PHASES.join(' → ')}\n`);
out.push('## Descriptors (deltas)\n');
for (const [k, v] of Object.entries(DESCRIPTORS)) out.push(`- **${k}**: ${Object.entries(v).map(([a, d]) => `${a} ${d >= 0 ? '+' : ''}${d}`).join(', ')}`);
out.push('\n## Overlays (emotion/genre, low confidence)\n');
for (const [k, v] of Object.entries(OVERLAYS)) out.push(`- **${k}**: ${Object.entries(v).map(([a, d]) => `${a} ${d >= 0 ? '+' : ''}${d}`).join(', ')}`);
out.push(`\n## Modifiers\n\n${Object.entries(MODIFIERS).map(([k, v]) => `${k} ×${v}`).join(', ')}; "less X" negates.`);
out.push('\n## Harmony words (states, not deltas; modifiers ignored)\n');
out.push('Write `key` and `progression` on the section. Numerals are diatonic to the section key; one chord per cycle unless bracketed; default `i VI`.\n');
for (const [k, v] of Object.entries(HARMONY.progressions)) out.push(`- **${k}**: ${v}`);
out.push(`- modes: ${HARMONY.modes.join(', ')} (keep the root, swap the mode)`);
out.push('- **relative**: relative major/minor of the current key; `relative major` = relative key then that mode');
out.push('- progression grammar: `b`/`#` before a numeral, `m`/`M`/`dim` after it, `7` (dominant on uppercase: `V7`; diatonic on lowercase: `ii7`) or `M7` (major seventh), `[..]` for several chords in one bar: `\'i bVI [III VII] V7\'`');
out.push('- not modeled: inversions, voice leading, chords longer than a bar. For other scales use a different section key (e.g. `C:harmonic minor`).');
out.push('\n## Movements (write a movement call around the axis\'s current value)\n');
const byFn = {};
for (const [word, fn] of Object.entries(MOTION)) (byFn[fn] ??= []).push(word);
for (const [fn, words] of Object.entries(byFn)) out.push(`- **${fn}**: ${words.join(', ')}`);
out.push('\nSignatures:');
out.push('- `wobble(a, b, bars=1)` — sine, one cycle of wobble per `bars`');
out.push('- `drift(a, b)` — smooth wandering noise (perlin)');
out.push('- `pulse(a, b, per=4)` — square, `per` beats per cycle');
out.push('- `swell(a, b)` — sine timed to the section, peaking a quarter of the way through');
out.push('- `rise`/`fall` write `ramp(v, v+.3)` / `ramp(v, v-.3)` from the axis\'s current value `v`, not a MOTION function');
console.log(out.join('\n'));
