// The undead cast: nineteen of the dead in the clothes they were buried in (the eighties pack), their rot the undead
// pack. Who they were is in `set`, the same structural pins the editorial archetypes carry, plus the dead skin, the
// milky eyes and the rotten teeth, as numbers and names on the identity and never a filter over the drawing; the rot is
// a list of home makeups, so it is their face in every shot, and the grave is on the clothes as marks a phase adds
// more of. The expressions hold no smile: `open` is the jaw, which the kick drops further (the dance's `motion.jaw`).
import '../parts/eighties.mjs'; import '../parts/undead.mjs'; // the parts this cast is made of register by name
import { ZOMBIE_SKINS, DEAD_EYES, EXTRA_MARKS } from '../parts/undead.mjs';
import { NEON } from '../parts/eighties.mjs';
import { COSTUMES, ARCHETYPES, EXPRESSIONS, WHITE } from '../cast.mjs';

// --- the wardrobe: what each of them was buried in ---
export const ZOMBIE_COSTUMES = {
  thrillerRed: () => ({ top: { style: 'crewTshirt', color: '#1a1618' }, jacket: { style: 'redLeatherChevron', color: NEON.red }, pants: { style: 'trousers', color: '#1a1618' } }),
  varsity: (v) => ({ top: { style: 'crewTshirt', color: WHITE }, jacket: { style: 'varsityJacket', color: v ? '#7a2a2a' : '#2a4f8f', accent: '#e9e2d0' } }),
  aerobics: () => ({ top: { style: 'leotard', color: NEON.pink, accent: NEON.teal }, jacket: { style: 'none' }, pants: { style: 'trousers', color: NEON.teal }, hat: { style: 'headband', color: NEON.teal, accent: NEON.yellow } }),
  flashdance: () => ({ top: { style: 'offShoulderSweat', color: '#8d8c87' }, jacket: { style: 'none' } }),
  tuxedo: () => ({ top: { style: 'ruffledTux', color: NEON.ivory, accent: '#5a1a2c' }, jacket: { style: 'blazer', color: '#1b1a1f' }, pants: { style: 'trousers', color: '#1b1a1f' }, accessories: ['tie'] }),
  powerSuit: () => ({ top: { style: 'crewTshirt', color: NEON.yellow, metal: 1 }, jacket: { style: 'padShoulderBlazer', color: NEON.purple }, pants: { style: 'skirt', color: NEON.purple } }),
  preppy: () => ({ top: { style: 'polo', color: '#e8c0b6' }, jacket: { style: 'sweaterShoulders', color: '#2f5d3a' } }),
  tracksuit: () => ({ top: { style: 'trackTop', color: NEON.blue, accent: NEON.yellow }, jacket: { style: 'none' }, pants: { style: 'trousers', color: NEON.blue }, hat: { style: 'headband', color: NEON.yellow, accent: NEON.blue } }),
  hospital: () => ({ top: { style: 'hospitalGown', color: '#bfd3cf' }, jacket: { style: 'none' }, pants: { style: 'skirt', color: '#bfd3cf' } }),
  bride: () => ({ top: { style: 'laceGown', color: NEON.ivory }, jacket: { style: 'none' }, pants: { style: 'skirt', color: NEON.ivory }, hat: { style: 'veil', color: '#f6f2ea', accent: '#d9c79a' }, props: ['veilBack'] }),
  punk: () => ({ top: { style: 'crewTshirt', color: '#1a1618', graphic: 'symbol' }, jacket: { style: 'leatherJacket', color: '#1d1b1e' } }),
  metal: (v) => ({ top: { style: 'crewTshirt', color: '#1a1618', graphic: v ? 'geometric' : 'strokes' }, jacket: { style: 'denimJacket', color: NEON.acid }, pants: { style: 'trousers', color: NEON.acid } }),
  disco: () => ({ top: { style: 'openShirt', color: '#c9a53a' }, jacket: { style: 'none' }, props: ['chain'] }),
  undertaker: () => ({ top: { style: 'buttonDown', color: '#dcd6c8' }, jacket: { style: 'trenchCoat', color: '#1f1d1f' }, hat: { style: 'wideBrimFelt', color: '#1c1a1c', accent: '#3a3436' } }),
  soldier: () => ({ top: { style: 'crewTshirt', color: '#5c6b4a' }, jacket: { style: 'fieldJacket', color: '#4a5a38' }, pants: { style: 'trousers', color: '#4a5a38' } }),
  newWave: () => ({ top: { style: 'buttonDown', color: '#f1eee9', accent: '#e0237a' }, jacket: { style: 'blazer', color: NEON.teal }, accessories: ['tie'] }),
  goth: () => ({ top: { style: 'turtleneck', color: '#141216' }, jacket: { style: 'none' }, pants: { style: 'skirt', color: '#141216' } }),
  surfer: () => ({ top: { style: 'openShirt', color: '#e07a8f' }, jacket: { style: 'none' } }),
  denimDiva: () => ({ top: { style: 'crewTshirt', color: '#c96a92' }, jacket: { style: 'denimJacket', color: '#9fb5c8' }, pants: { style: 'trousers', color: '#9fb5c8' } }),
};
Object.assign(COSTUMES, ZOMBIE_COSTUMES);
export const ZOMBIE_COSTUME_NAMES = Object.keys(ZOMBIE_COSTUMES);

// --- the cast: who they were, in `set` the same structural pins the editorial archetypes carry, plus the dead skin, the milky eyes and the rotten teeth ---
const dead = (skin, eyes = {}, mouth = {}) => ({ skin, eyes: { ...DEAD_EYES, ...eyes }, mouth: { teeth: 'rotten', ...mouth } });
export const ZOMBIES = {
  thrillerLead: { beard: 'none', family: 'squareJaw', hair: 'curlyMedium', hairColors: ['jetBlack'], costume: 'thrillerRed', makeup: ['ashenSockets', 'gauntCheeks', 'rotLips'], marks: 'none', set: { ...dead(ZOMBIE_SKINS[0], { spacing: 54, openness: 1.05 }), face: { width: 164, height: 210, chin: 0.2 }, nose: { style: 'straight', width: 20, length: 42 }, mouth: { width: 50, fullness: 0.5, teeth: 'rotten' }, neck: { width: 64, height: 74 }, body: { width: 1.05 }, pose: { turn: 0.2, shoulder: 0.3 } } },
  varsityJock: { beard: 'none', family: 'heavyBrow', hair: 'crewCut', hairColors: ['darkBlond', 'lightBrown'], costume: 'varsity', makeup: ['exposedJaw', 'ashenSockets'], marks: 'graveDirt', set: { ...dead(ZOMBIE_SKINS[1], { spacing: 44, depth: 1, openness: 0.8 }), face: { width: 186, height: 196, corner: 46, jaw: 0.72 }, nose: { style: 'broad', width: 30, length: 36 }, mouth: { style: 'wide', width: 54, fullness: 0.2, teeth: 'rotten' }, neck: { width: 92, height: 52 }, body: { width: 1.45 }, pose: { turn: 0.4, shoulder: -0.6, headTilt: -0.08 } } },
  aerobicsInstructor: { beard: 'none', family: 'wideCheek', hair: 'bigHair', hairColors: ['auburn', 'blond'], costume: 'aerobics', makeup: ['veinedTemples', 'drool', 'ashenSockets'], marks: 'none', set: { ...dead(ZOMBIE_SKINS[2], { spacing: 60, openness: 1.25 }, { open: 0.3 }), face: { width: 168, height: 190, chin: 0.1 }, nose: { style: 'upturned', width: 20, length: 28 }, mouth: { style: 'wide', width: 52, fullness: 0.6, teeth: 'rotten' }, neck: { width: 60, height: 60 }, body: { width: 0.9 }, pose: { turn: -0.3, headTilt: 0.14, bodyTilt: -0.06 } } },
  flashdancer: { beard: 'none', family: 'fineBoned', hair: 'wavyMedium', hairColors: ['darkBrown', 'espresso'], costume: 'flashdance', makeup: ['gauntCheeks', 'cheekGash', 'rotLips'], marks: 'graveDirt', set: { ...dead(ZOMBIE_SKINS[5], { spacing: 56, openness: 1.1 }), face: { width: 150, height: 214, chin: 0.26 }, nose: { style: 'narrow', width: 15, length: 44 }, mouth: { width: 44, fullness: 0.7, teeth: 'rotten' }, neck: { width: 52, height: 92 }, body: { width: 0.84 }, pose: { turn: 0.5, shoulder: 0.7, headTilt: 0.12 } } },
  tuxGroom: { family: 'longMidface', hair: 'middlePart', hairColors: ['espresso', 'jetBlack'], beard: 'mustache', costume: 'tuxedo', makeup: ['rotLips', 'bloodMouth', 'ashenSockets'], marks: 'bloodSplatter', set: { ...dead(ZOMBIE_SKINS[3], { spacing: 48, openness: 0.9 }), face: { width: 146, height: 230, chin: 0.25 }, nose: { style: 'long', width: 16, length: 52 }, mouth: { style: 'thin', width: 42, fullness: 0.15, teeth: 'rotten' }, neck: { width: 54, height: 96 }, body: { width: 1 }, pose: { turn: 0.3, shoulder: 0.6, headTilt: 0.14 } } },
  powerExec: { beard: 'none', family: 'squareJaw', hair: 'bluntBob', hairColors: ['platinum'], costume: 'powerSuit', makeup: ['stitchedBrow', 'peelingSkin', 'ashenSockets'], marks: 'none', set: { ...dead(ZOMBIE_SKINS[4], { spacing: 62, openness: 1 }), face: { width: 170, height: 196, chin: 0.3 }, nose: { style: 'straight', width: 18, length: 38 }, mouth: { style: 'full', width: 50, fullness: 0.9, teeth: 'rotten' }, neck: { width: 60, height: 70 }, body: { width: 1.3 }, pose: { turn: -0.35, headTilt: -0.1, shoulder: -0.4 } } },
  preppy: { beard: 'none', family: 'roundSoft', hair: 'sidePart', hairColors: ['lightBrown', 'darkBlond'], costume: 'preppy', makeup: ['gauntCheeks', 'drool'], marks: 'mossStreaks', set: { ...dead(ZOMBIE_SKINS[1], { spacing: 58, openness: 0.85 }, { open: 0.2 }), face: { width: 176, height: 190, chin: 0.06, jaw: 0.95 }, nose: { style: 'roundedTip', width: 26, length: 32 }, mouth: { width: 44, fullness: 0.6, teeth: 'rotten' }, neck: { width: 78, height: 50 }, body: { width: 1.1 }, pose: { turn: 0.25, bodyTilt: 0.07, headTilt: 0.06 } } },
  jogger: { beard: 'none', family: 'wideCheek', hair: 'afroShort', hairColors: ['jetBlack'], costume: 'tracksuit', makeup: ['veinedTemples', 'ashenSockets', 'foreheadGash'], marks: 'none', set: { ...dead(ZOMBIE_SKINS[8], { spacing: 64, openness: 1.1 }), face: { width: 160, height: 204 }, nose: { style: 'short', width: 22, length: 30 }, mouth: { style: 'wide', width: 46, fullness: 0.6, teeth: 'rotten' }, neck: { width: 56, height: 72 }, body: { width: 0.95 }, pose: { turn: -0.45, shoulder: 0.5, headTilt: 0.1 } } },
  patient: { family: 'longMidface', hair: 'shavedHead', hairColors: ['gray', 'saltPepper'], age: 'old', costume: 'hospital', makeup: ['ashenSockets', 'stitchedBrow', 'drool', 'gauntCheeks'], marks: 'bloodSplatter', set: { ...dead(ZOMBIE_SKINS[6], { spacing: 54, openness: 0.8 }, { open: 0.25 }), face: { width: 142, height: 226, chin: 0.24 }, nose: { style: 'aquiline', width: 20, length: 54 }, mouth: { style: 'thin', width: 40, fullness: 0.15, teeth: 'rotten' }, neck: { width: 48, height: 86 }, body: { width: 0.9 }, pose: { headTilt: 0.18, shoulder: -0.5, turn: 0.2 } } },
  bride: { beard: 'none', family: 'fineBoned', hair: 'bigHair', hairColors: ['platinum', 'white'], costume: 'bride', makeup: ['ashenSockets', 'rotLips', 'cheekGash'], marks: 'graveDirt', set: { ...dead(ZOMBIE_SKINS[9], { spacing: 62, openness: 1.15 }), face: { width: 158, height: 206, chin: 0.3 }, nose: { style: 'short', width: 17, length: 30 }, mouth: { style: 'cupidBow', width: 46, fullness: 0.8, teeth: 'rotten' }, neck: { width: 50, height: 84 }, body: { width: 0.8 }, pose: { turn: 0.3, headTilt: -0.14, shoulder: 0.3 } } },
  punk: { family: 'heavyBrow', hair: 'shortMohawk', hairColors: ['jetBlack'], beard: 'lightStubble', costume: 'punk', makeup: ['exposedJaw', 'veinedTemples', 'blackEye'], marks: 'tornShirt', set: { ...dead(ZOMBIE_SKINS[7], { spacing: 46, depth: 1, openness: 0.85 }), face: { width: 168, height: 206, corner: 40 }, nose: { style: 'broad', width: 26, length: 38 }, mouth: { style: 'asym', width: 48, fullness: 0.4, teeth: 'rotten' }, neck: { width: 70, height: 66 }, body: { width: 1.1 }, pose: { turn: 0.55, shoulder: -0.6, headTilt: -0.06 } } },
  metalhead: { family: 'squareJaw', hair: 'mullet', hairColors: ['darkBrown', 'brown'], beard: 'heavyStubble', costume: 'metal', makeup: ['peelingSkin', 'ashenSockets', 'rotLips'], marks: ['tornShirt', 'graveDirt'], set: { ...dead(ZOMBIE_SKINS[3], { spacing: 50, openness: 0.9 }), face: { width: 178, height: 200, corner: 44, chin: 0.05 }, nose: { style: 'straight', width: 22, length: 40 }, mouth: { style: 'wide', width: 52, fullness: 0.4, teeth: 'rotten' }, neck: { width: 76, height: 62 }, body: { width: 1.2 }, pose: { turn: -0.5, shoulder: 0.6, headTilt: 0.08 } } },
  discoGhoul: { family: 'wideCheek', hair: 'sweptBack', hairColors: ['espresso'], beard: 'mustache', costume: 'disco', makeup: ['gauntCheeks', 'rotLips', 'bloodMouth'], marks: 'none', set: { ...dead(ZOMBIE_SKINS[5], { spacing: 56, openness: 0.95 }), face: { width: 164, height: 206, chin: 0.22 }, nose: { style: 'aquiline', width: 18, length: 46 }, mouth: { width: 48, fullness: 0.5, teeth: 'rotten' }, neck: { width: 62, height: 76 }, body: { width: 1 }, pose: { turn: 0.6, shoulder: -0.5, headTilt: 0.06 } } },
  undertaker: { family: 'longMidface', hair: 'receding', hairColors: ['saltPepper', 'gray'], beard: 'garibaldi', age: 'old', costume: 'undertaker', makeup: ['ashenSockets', 'gauntCheeks', 'veinedTemples'], marks: 'dustShoulders', set: { ...dead(ZOMBIE_SKINS[7], { spacing: 52, depth: 1, openness: 0.8 }), face: { width: 148, height: 232, chin: 0.24 }, nose: { style: 'aquiline', width: 20, length: 56 }, mouth: { style: 'thin', width: 40, fullness: 0.15, teeth: 'rotten' }, neck: { width: 50, height: 100 }, body: { width: 1 }, pose: { headTilt: 0.1, shoulder: -0.4, turn: 0.25 } } },
  soldier: { family: 'squareJaw', hair: 'crewCut', hairColors: ['brown', 'darkBrown'], costume: 'soldier', makeup: ['foreheadGash', 'ashenSockets', 'exposedJaw'], marks: ['bloodSplatter', 'graveDirt'], set: { ...dead(ZOMBIE_SKINS[0], { spacing: 50, openness: 0.95 }), face: { width: 180, height: 204, corner: 44, chin: 0.08 }, nose: { style: 'straight', width: 22, length: 40 }, mouth: { width: 48, fullness: 0.35, teeth: 'rotten' }, neck: { width: 80, height: 60 }, body: { width: 1.3 }, pose: { turn: 0.2, shoulder: 0.3 } } },
  newWaver: { beard: 'none', family: 'fineBoned', hair: 'shortTextured', hairColors: ['platinum', 'lightBlond'], costume: 'newWave', makeup: ['cheekGash', 'rotLips', 'veinedTemples'], marks: 'none', set: { ...dead(ZOMBIE_SKINS[2], { spacing: 58, openness: 1.1 }), face: { width: 156, height: 212, chin: 0.26 }, nose: { style: 'narrow', width: 15, length: 42 }, mouth: { width: 44, fullness: 0.5, teeth: 'rotten' }, neck: { width: 56, height: 80 }, body: { width: 0.92 }, pose: { turn: -0.4, headTilt: 0.12, shoulder: 0.5 } } },
  goth: { beard: 'none', family: 'longMidface', hair: 'bluntBob', hairColors: ['jetBlack'], costume: 'goth', makeup: ['ashenSockets', 'rotLips', 'peelingSkin'], marks: 'none', set: { ...dead(ZOMBIE_SKINS[4], { spacing: 50, openness: 1.05 }), face: { width: 148, height: 222, chin: 0.24 }, nose: { style: 'long', width: 16, length: 48 }, mouth: { style: 'full', width: 42, fullness: 0.8, teeth: 'rotten' }, neck: { width: 50, height: 94 }, body: { width: 0.88 }, pose: { headTilt: -0.12, turn: 0.35, shoulder: -0.3 } } },
  surfer: { beard: 'none', family: 'wideCheek', hair: 'longStraight', hairColors: ['lightBlond', 'blond'], costume: 'surfer', makeup: ['gauntCheeks', 'drool', 'veinedTemples'], marks: 'mossStreaks', set: { ...dead(ZOMBIE_SKINS[1], { spacing: 60, openness: 0.9 }, { open: 0.2 }), face: { width: 170, height: 200, chin: 0.1 }, nose: { style: 'short', width: 22, length: 32 }, mouth: { style: 'wide', width: 50, fullness: 0.55, teeth: 'rotten' }, neck: { width: 66, height: 66 }, body: { width: 1.15 }, pose: { turn: -0.3, bodyTilt: -0.08, headTilt: 0.1 } } },
  denimDiva: { beard: 'none', family: 'wideCheek', hair: 'bigHair', hairColors: ['auburn', 'copper'], accessories: ['hoopLeft', 'hoopRight'], costume: 'denimDiva', makeup: ['ashenSockets', 'cheekGash', 'rotLips'], marks: 'dustShoulders', set: { ...dead(ZOMBIE_SKINS[6], { spacing: 60, openness: 1.2 }), face: { width: 172, height: 198, chin: 0.3 }, nose: { style: 'short', width: 19, length: 28 }, mouth: { style: 'full', width: 54, fullness: 1, teeth: 'rotten' }, neck: { width: 56, height: 72 }, body: { width: 0.95 }, pose: { bodyTilt: -0.09, turn: 0.45, headTilt: -0.1 } } },
};
Object.assign(ARCHETYPES, ZOMBIES);
export const ZOMBIE_NAMES = Object.keys(ZOMBIES);

// --- the faces they hold: no smile among them; `open` is the jaw, which the kick drops further (tableau's `motion.jaw`) ---
export const ZOMBIE_EXPRESSIONS = {
  slackJaw: { eyes: { openness: 0.9, browLift: 1 }, mouth: { smile: -0.25, open: 0.35 } },
  deadStare: { eyes: { openness: 1.2, browLift: -1 }, mouth: { smile: -0.15, open: 0.08 } },
  hunger: { eyes: { openness: 1.1, browLift: 3 }, mouth: { smile: 0.1, open: 0.5 } },
  snarl: { eyes: { openness: 0.75, browLift: -4, browSkew: 0.3 }, mouth: { style: 'asym', smile: -0.3, open: 0.25 } },
  moan: { eyes: { openness: 0.55, browLift: 4 }, mouth: { smile: -0.1, open: 0.6 } },
  lidsHalf: { eyes: { openness: 0.45 }, mouth: { smile: -0.2, open: 0.15 } },
};
Object.assign(EXPRESSIONS, ZOMBIE_EXPRESSIONS);
const EXPR_POOL = ['slackJaw', 'slackJaw', 'deadStare', 'hunger', 'snarl', 'moan', 'lidsHalf'], EMOTES = ['slackJaw', 'deadStare', 'hunger', 'moan', 'lidsHalf'];

export default { name: 'undead', archetypes: ZOMBIES, archetypeNames: ZOMBIE_NAMES, costumes: ZOMBIE_COSTUME_NAMES, expressions: EXPR_POOL, emotes: EMOTES, extraMarks: EXTRA_MARKS, build: 'default' };
